# https://golangci-lint.run/usage/configuration

run:
  # Define the Go version limit.
  go: '1.17'

  # Include test files or not.
  tests: false

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errorlint
    - exportloopref
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goimports
    - gosec
    - lll
    - nakedret
    - nilerr
    - noctx
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - wastedassign
    - whitespace
