// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package openapi

import (
	"context"
	"sync"

	"github.com/sknv/passwordless-verifier/internal/model"
	"github.com/sknv/passwordless-verifier/internal/usecase"
)

// Ensure, that UsecaseMock does implement Usecase.
// If this is not the case, regenerate this file with moq.
var _ Usecase = &UsecaseMock{}

// UsecaseMock is a mock implementation of Usecase.
//
// 	func TestSomethingThatUsesUsecase(t *testing.T) {
//
// 		// make and configure a mocked Usecase
// 		mockedUsecase := &UsecaseMock{
// 			CreateVerificationFunc: func(ctx context.Context, newVerification *usecase.NewVerification) (*model.Verification, error) {
// 				panic("mock out the CreateVerification method")
// 			},
// 		}
//
// 		// use mockedUsecase in code that requires Usecase
// 		// and then make assertions.
//
// 	}
type UsecaseMock struct {
	// CreateVerificationFunc mocks the CreateVerification method.
	CreateVerificationFunc func(ctx context.Context, newVerification *usecase.NewVerification) (*model.Verification, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateVerification holds details about calls to the CreateVerification method.
		CreateVerification []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// NewVerification is the newVerification argument value.
			NewVerification *usecase.NewVerification
		}
	}
	lockCreateVerification sync.RWMutex
}

// CreateVerification calls CreateVerificationFunc.
func (mock *UsecaseMock) CreateVerification(ctx context.Context, newVerification *usecase.NewVerification) (*model.Verification, error) {
	if mock.CreateVerificationFunc == nil {
		panic("UsecaseMock.CreateVerificationFunc: method is nil but Usecase.CreateVerification was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		NewVerification *usecase.NewVerification
	}{
		Ctx:             ctx,
		NewVerification: newVerification,
	}
	mock.lockCreateVerification.Lock()
	mock.calls.CreateVerification = append(mock.calls.CreateVerification, callInfo)
	mock.lockCreateVerification.Unlock()
	return mock.CreateVerificationFunc(ctx, newVerification)
}

// CreateVerificationCalls gets all the calls that were made to CreateVerification.
// Check the length with:
//     len(mockedUsecase.CreateVerificationCalls())
func (mock *UsecaseMock) CreateVerificationCalls() []struct {
	Ctx             context.Context
	NewVerification *usecase.NewVerification
} {
	var calls []struct {
		Ctx             context.Context
		NewVerification *usecase.NewVerification
	}
	mock.lockCreateVerification.RLock()
	calls = mock.calls.CreateVerification
	mock.lockCreateVerification.RUnlock()
	return calls
}
