// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package application

import (
	"context"
	"sync"
)

// Ensure, that WorkerMock does implement Worker.
// If this is not the case, regenerate this file with moq.
var _ Worker = &WorkerMock{}

// WorkerMock is a mock implementation of Worker.
//
// 	func TestSomethingThatUsesWorker(t *testing.T) {
//
// 		// make and configure a mocked Worker
// 		mockedWorker := &WorkerMock{
// 			CloseFunc: func(ctx context.Context) error {
// 				panic("mock out the Close method")
// 			},
// 			RunFunc: func(ctx context.Context)  {
// 				panic("mock out the Run method")
// 			},
// 		}
//
// 		// use mockedWorker in code that requires Worker
// 		// and then make assertions.
//
// 	}
type WorkerMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func(ctx context.Context) error

	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockClose sync.RWMutex
	lockRun   sync.RWMutex
}

// Close calls CloseFunc.
func (mock *WorkerMock) Close(ctx context.Context) error {
	if mock.CloseFunc == nil {
		panic("WorkerMock.CloseFunc: method is nil but Worker.Close was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc(ctx)
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//     len(mockedWorker.CloseCalls())
func (mock *WorkerMock) CloseCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Run calls RunFunc.
func (mock *WorkerMock) Run(ctx context.Context) {
	if mock.RunFunc == nil {
		panic("WorkerMock.RunFunc: method is nil but Worker.Run was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	mock.RunFunc(ctx)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//     len(mockedWorker.RunCalls())
func (mock *WorkerMock) RunCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
