[app]
name = "passwordless_verifier"

[log]
level = "debug"

[http]
address = ":8080"

[jaeger]
host = "localhost"
port = "6831"
ratio = 1.0 # 1.0 means trace every time, 0.0 - no tracing at all

[postgres]
url = "postgres://root:root@localhost:26257/postgres?sslmode=disable"
max_open_conn = 10 # default is 10 per CPU
max_conn_lifetime = "10m"
